### ISSUE TITLE
pkg-config

### ISSUE THREAD

**Issue by pellsson** [kerberizer/llvm-svn#17]
Ran it on a new system without pkg-config which failed. Would probably be nice to add pkg-config as a dependency.

Also, for whatever reason I had to manually install libffi, kinda strange as it seems to be included as a dependency. Had no time to investigate really.

Anyhow, thank you for a very nice package :) 👍

**Comment by SolarAquarion** [comment]
pkg-config is in base-devel

**Comment by kerberizer** [comment]
pkg-config is indeed in base-devel and base-devel packages [must not](https://wiki.archlinux.org/index.php/PKGBUILD#makedepends) be included as make dependencies. As for libffi, this is really strange and isn't supposed to happen. If you find a real problem with the package behind it, don't hesitate to reopen the issue. Even if you just find what the cause was, please do post it here so that others may benefit if stumbling upon a similar issue. Thanks! :)
